name: Update docs-dist


on:
  push:
    # æ¨é€åˆ†æ”¯æ—¶è§¦å‘
    branches: [ action ]

jobs:
  update-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@action

      - name: install
        run: yarn
        
      - name: build
        run: yarn docs:build

      - name: deploy
        run: yarn docs:deploy
      
      - name: Commit and push if changed
        run: |-
          git diff
          # è®¾ç½®è‡ªå·±çš„ç”¨æˆ·å é‚®ç®±
          git config --global user.email "animas@126.com"
          git config --global user.name "animasling"
          git pull
          git add -A
          git commit -m "ğŸ¤– auto: updated dist" || exit 0
          git push
